### ISSUE TITLE
Unable to get this working with HAproxy v2.4

### ISSUE THREAD

**Issue by yasiemir** [haproxytech/haproxy-lua-oauth#12]
HAproxy v2.4 is getting Lua Runtime Error
```
Lua runtime error: error loading module '_openssl.pkey' from file '/usr/local/lib/lua/5.4/_openssl.so':
        /usr/local/lib/lua/5.4/_openssl.so: undefined symbol: lua_setuservalue
```
The same setup is working fine with HAproxy 1.9.1

**Comment by NickMRamirez** [comment]
HAProxy 2.4 is still under development. We should revisit this once it is released.

**Comment by NickMRamirez** [comment]
I am revisiting this now that HAProxy 2.4 has been released.

I do not get the error, is it still happening for you? I've updated the [example here](https://github.com/haproxytechblog/haproxy-jwt-vagrant) to use HAProxy 2.4.
