### ISSUE TITLE
Google OAuth based example

### ISSUE THREAD

**Issue by rgarrigue** [haproxytech/haproxy-lua-oauth#16]
Hi there

I'ld like to replace our basic auth by a Google based OAuth. This look like the way to go, but I'm a bit lost adapting the Auth0 based explanations to Google's auth stuff. So in case you tried it, mind sharing notes about it ? That would also make a fine documentation with some polish :)

Best regards,

**Comment by NickMRamirez** [comment]
Hi @rgarrigue I have not tried it with Google, but it depends on the OAuth 2 workflow you want to implement. My experience is with machine-to-machine authentication using the Client Credentials grant workflow. For that, I found this link: https://cloud.google.com/apigee/docs/api-platform/security/oauth/oauth-20-client-credentials-grant-type

For other grant workflows, such as logging in human users, I am not sure, but the project would benefit from any documentation you discover.

**Comment by NickMRamirez** [comment]
Closing this issue, but please re-open if needed.
