### ISSUE TITLE
print_help function missing

### ISSUE THREAD

**Issue by squawk979** [haproxytech/haproxy-lua-oauth#19]
just a minor gripe:  if an unexpected argument is passed to install.sh it results in this error:

./install.sh: line 164: print_help: command not found

as there is no print_help function

**Comment by NickMRamirez** [comment]
That's a good observation. The script is lacking things like that. To be honest, I've wanted to strip out the parts that install HAProxy, just to simplify it. Then, once it's more simple, we could add a print help function.

**Comment by NickMRamirez** [comment]
This should now be fixed.
