### ISSUE TITLE
Must config a OAUTH_PUBKEY_PATH with valid file even in JWT only sceanrio

### ISSUE THREAD

**Issue by dabdirb** [haproxytech/haproxy-lua-oauth#23]
I use haproxy with only JWT verify without OAuth, so i have no OAUTH_PUBKEY_PATH  to configure, it will cause exception when initialize the config.
To workaround this issue, i must config a valid OAUTH_PUBKEY_PATH !

**Comment by NickMRamirez** [comment]
This library is specifically for OAuth and other uses of JWT are not supported.
