### ISSUE TITLE
errors on RHEL8 HA-Proxy version 1.8.27-493ce0b 2020/11/06

### ISSUE THREAD

**Issue by yvanadamov** [haproxytech/haproxy-lua-oauth#29]
Hi, 

I got the following error:

1) When I try to load jwtverify.lua in global section:
 Starting HAProxy Load Balancer...
Mar 08 19:20:02 r5testsapp1 haproxy[715142]: [ALERT] 066/192002 (715142) : parsing [/etc/haproxy/haproxy.cfg:10] : lua runtime error: /usr/local/share/lua/5.>Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no field package.preload['openssl.pkey']
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file '/usr/share/lua/5.3/openssl/pkey.lua'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file '/usr/share/lua/5.3/openssl/pkey/init.lua'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file '/usr/lib64/lua/5.3/openssl/pkey.lua'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file '/usr/lib64/lua/5.3/openssl/pkey/init.lua'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file './openssl/pkey.lua'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file './openssl/pkey/init.lua'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file '/usr/lib64/lua/5.3/openssl/pkey.so'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file '/usr/lib64/lua/5.3/loadall.so'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file './openssl/pkey.so'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file '/usr/lib64/lua/5.3/openssl.so'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file '/usr/lib64/lua/5.3/loadall.so'
Mar 08 19:20:02 r5testsapp1 haproxy[715142]:         no file './openssl.so'

Best regards,
Ivan Adamov

**Comment by NickMRamirez** [comment]
The install script runs this to install the Lua OpenSSL dependency:

```
curl -sLO https://github.com/wahern/luaossl/archive/refs/heads/master.zip
    unzip -qo master.zip && rm master.zip
    cd luaossl-master/
    make install
```

If you run this yourself, do you get errors?

**Comment by NickMRamirez** [comment]
I found the problem and fixed the install script to work on RHEL and CentOS.
