### ISSUE TITLE
Haproxy-lua-oauth and Centos 7

### ISSUE THREAD

**Issue by CanadianHorseman** [haproxytech/haproxy-lua-oauth#30]
Hello
I'm struggling to get Haproxy-lua-oauth working with Centos 7.
I have fixed install.sh to provide dependences.
But haproxy won't run anyways:

[ALERT] 184/181506 (969) : parsing [/etc/haproxy/haproxy.conf:10] : Lua runtime error: error loading module 'mime.core' from file '/usr/local/lib/lua/5.3/mime/core.so':
        /usr/local/lib/lua/5.3/mime/core.so: undefined symbol: luaL_prepbuffer

and then http-request won't take lua.jwtverify
      
HA-Proxy version 2.3.2-d522db7

Is there a way to get it working with Centos 7?

**Comment by NickMRamirez** [comment]
I can reproduce this error. I am looking into it.

**Comment by NickMRamirez** [comment]
I think it was caused by the dependencies not installing correctly, but after reproducing the issue once, I wasn't able to reproduce it again. Maybe the latest change will fix the problem. Could you try re-installing?

**Comment by CanadianHorseman** [comment]
It seems it does work now. Thank you!
