### ISSUE TITLE
Is there a way to install this in pfsense (FreeBSD) ?

### ISSUE THREAD

**Issue by brycelarge** [haproxytech/haproxy-lua-oauth#32]
Hi there,

I wanted to install your package on my haproxy which is running on my pfsense, I was wondering if you have done so before and if you perhaps have some install instructions for me?

**Comment by NickMRamirez** [comment]
I don't have experience with pfsense myself. Maybe someone on the HAProxy Slack does?

**Comment by brycelarge** [comment]
thanks. Im attempting to see if I can update the install script to work in freeBSD, if I get it working Ill open a PR.
