### ISSUE TITLE
H2 response from service

### ISSUE THREAD

**Issue by Muhammad-1990** [haproxytech/haproxy-lua-oauth#33]
Hi,
Is it possible to return a h2 response inside 'register_service'?

i have a grpc client calling haproxy that forwards the request to a backend grpc server.
all works fine.

if for some reason i want to deny the request, the deny directive doesnt give the grpc client much info what went wrong. how do i provide more info? (currently setting headers in a service)

this doesnot work:
```http-request deny deny_status 429 content-type text/plain lf-string "too_many_requests" ```
i was hoping i could construct a h2 response from inside a service?

something like...

```
local protobuf = require('protobuf')
    local input = { code = "403", message = "denied" }
    local message = pb.encode('api.v1.status', input)
    local data = "\x00"..message

applet:add_header("content-type", "application/grpc+proto")
applet:start_response()
applet:send([headers])
applet:send("data ")
```

**Comment by NickMRamirez** [comment]
Right, HAProxy currently has limited support for gRPC. It can extract fields from a ProtoBuf message (see the [protobuf method](http://docs.haproxy.org/2.8/configuration.html#protobuf) and u[ngrpc method](http://docs.haproxy.org/2.8/configuration.html#ungrpc)), but it lacks the ability to write ProtoBuf itself. Creating a Lua module to do this, as you're demonstrating, could work. I have no experience doing this, and the haproxy-lua-oauth library here doesn't include any gRPC feature.

I am curious to see how this would work, and I am cheering you on, even though I can't be of immediate help.

**Comment by Muhammad-1990** [comment]
Technically I can call an upstream service just to get a formatted error and return that. but it would be too easy and who really wants to deal with another _"we dont need more microservices"_ lecture ... h2 is actually quiet complex... Anywho, here is a very good starting point should anyone come here looking for tips. [lukego/grpc_assets.lua](https://gist.github.com/lukego/e3cc201f4cae43dc9825322c8314028d)

thanks though, guess we can close this off until theres some ground breaking updates...

**Comment by NickMRamirez** [comment]
Thanks for sharing this @Muhammad-1990 . It's an interesting use case. I will close this issue, but it may be worthwhile to stick your lua file into a repo for others seeking an haproxy-grpc solution.
