### ISSUE TITLE
Example lacks info on HMAC secret configuration

### ISSUE THREAD

**Issue by tmarkunin** [haproxytech/haproxy-lua-oauth#35]
Hello!

Can you please add instructions on how to configure example for HS256?
Should OAUTH_HMAC_SECRET environment variable be set to the same public key that was generated in Auth0?

- Thanks in advance

**Comment by NickMRamirez** [comment]
Hi @tmarkunin There's an example at https://github.com/haproxytech/haproxy-lua-oauth/blob/53d5e26e7aa727162f2fe89881efb191416d8f05/haproxy-example.cfg#L11

Instead of setting it to a public key, you will set it to a shared secret. It's a string.
