### ISSUE TITLE
Docker Compose error:  Lua runtime error: error loading module '_openssl.pkey' 

### ISSUE THREAD

**Issue by tmarkunin** [haproxytech/haproxy-lua-oauth#36]
Hello,
I would like to thank you for this great opensource project, it helped me a lot.
I'm experiencing the same issue as https://github.com/haproxytech/haproxy-lua-oauth/issues/31 but using example with Docker Compose:

```
haproxy-lua-oauth-haproxy-1  | [NOTICE]   (1) : haproxy version is 2.6.15-446b02c
haproxy-lua-oauth-haproxy-1  | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
haproxy-lua-oauth-haproxy-1  | [ALERT]    (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:8] : Lua runtime error: error loading module '_openssl.pkey' from file '/usr/local/lib/lua/5.3/_openssl.so':
haproxy-lua-oauth-haproxy-1  |  /usr/local/lib/lua/5.3/_openssl.so: undefined symbol: lua_newuserdata
```

**Comment by NickMRamirez** [comment]
@tmarkunin It looks like they updated the `haproxytech/haproxy-ubuntu:2.6` Docker container to use Lua 2.4.4. I've updated the example to work with that and pushed the update to the master branch. Please let me know if this resolves the issue.

**Comment by tmarkunin** [comment]
Thanks @NickMRamirez ! It looks like it fixed the issue.
